site_name: Sensor Network Documentation
theme: 
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  # Extra features
  features:
    # ---------------------
    # Navigation
    # ---------------------
    # Search index survives navigation
  - navigation.instant
    # The URL in the address bar is automatically updated with scroll
  - navigation.tracking
    # Top address bar with sections
    #- navigation.tabs
    # Bold level 2 sections in left bar
  - navigation.sections
    # Documents can be directly attached to sections (see https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages)
  #- navigation.indexes
    # Automatic left bar scroll
  - toc.follow
    # Back to top button
  - navigation.top
    # ---------------------
    # Search
    # ---------------------
    # Search suggestions in search button
  - search.suggest
  - search.highlight
    # Allow sharing a search result
  - search.share
plugins:
  - monorepo
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang:
      - en
      - pt
extra:
  # ---------------------
  # Remove the 'made with mkdocs'
  # ---------------------
  generator: false

nav:
  - Introduction: 'index.md'
  - Getting Started:
    - Repository Structure: 'pages/repo_structure.md'
    - Install Guide: 'pages/install_guide.md'
    - Example Usage: 'pages/example_usage.md'
  - Packages Documentation:
    - Node: '!include ./node/mkdocs.yml'
    - Gateway: '!include ./gateway_serial/mkdocs.yml'